{
	"Properties": {
		"Description": "Test MDK - Ashok",
		"FinishDate": "",
		"FinishTime": "",
		"Operation": "#Property:OperationNo",
		"OrderID": "#Property:OrderId",
		"StartDate": "/SAPAssetManager/Rules/DateTime/CurrentDateTime.js",
		"StartTime": "/SAPAssetManager/Rules/DateTime/CurrentTime.js"
	},
	"Target": {
		"EntitySet": "Confirmations",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}