{
	"CreateLinks": [
		{
			"Property": "WorkOrderOperation",
			"Target": {
				"EntitySet": "MyWorkOrderOperations"
			},
			"_Enabled": true
		}
	],
	"Properties": {
		"ConfirmationCounter": "",
		"ConfirmationNum": "",
		"Description": "Test Ashok MDK Action",
		"Operation": "0060",
		"OrderID": "4000341",
		"OrderType": ""
	},
	"Target": {
		"EntitySet": "Confirmations",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}