{
	"PopoverItems": [
		{
			"Enabled": "/SAPAssetManager/Rules/WorkOrders/Operations/AutoTimeEntry/StartEnable.rule.js",
			"Icon": "/SAPAssetManager/Images/Start.png",
			"OnPress": "/SAPAssetManager/Rules/WorkOrders/Operations/AutoTimeEntry/AutoTimeStart.rule.js",
			"Title": "$(L,start)",
			"Visible": true
		},
		{
			"Enabled": "/SAPAssetManager/Rules/WorkOrders/Operations/AutoTimeEntry/PauseEnable.rule.js",
			"Icon": "/SAPAssetManager/Images/Pause.png",
			"OnPress": "/SAPAssetManager/Rules/WorkOrders/Operations/AutoTimeEntry/AutoTimePause.rule.js",
			"Title": "$(L,pause)",
			"Visible": true
		},
		{
			"Enabled": "/SAPAssetManager/Rules/WorkOrders/Operations/AutoTimeEntry/StopEnable.rule.js",
			"Icon": "/SAPAssetManager/Images/Stop.png",
			"OnPress": "/SAPAssetManager/Rules/WorkOrders/Operations/AutoTimeEntry/AutoTimeStop.rule.js",
			"Title": "$(L,stop)",
			"Visible": true
		}
	],
	"Title": "Automatic Time Entry",
	"_Type": "Action.Type.PopoverMenu"
}