{
    "_Type": "Action.Type.ODataService.CreateMedia",
    "Target" : {
      "EntitySet" : "Documents",
      "Service" : "/SAPAssetManager/Services/AssetManager.service"
    },
    "Headers" : {
       "slug" : {
          "ObjectLink":"/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateObjectLink.js",
          "ObjectKey": "/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateKey.js",
          "FileName": "/SAPAssetManager/Rules/Documents/Create/DocumentCreateFilename.js",
          "Description": "/SAPAssetManager/Rules/Documents/Create/OnCreateGetDocDescription.js"
      }
    },
    "Properties" : {
        "ObjectLink": "/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateObjectLink.js",
        "ObjectKey": "/SAPAssetManager/Rules/Documents/DocumentTransactionID.js",
        "FileName": "/SAPAssetManager/Rules/Documents/Create/DocumentCreateFilename.js",
        "Description": "/SAPAssetManager/Rules/Documents/Create/OnCreateGetDocDescription.js",
        "MimeType": "image"
    },
    "IsOnlineRequest": false,
    "Media":"/SAPAssetManager/Rules/Documents/Create/OnCreateGetDoc.js",
    "OnSuccess": "/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateLink.js",
    "OnFailure": "/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateFailure.js"
  }