{
	"OnSuccess": "/SAPAssetManager/Rules/Documents/Create/DocumentCreateDelete.js",
	"Target": {
		"EntitySet": "/SAPAssetManager/Rules/Equipment/DocumentAddEditEntitySet.js",
		"ReadLink": "{@odata.readLink}",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"ValidationRule": "/SAPAssetManager/Rules/Equipment/DocumentAddEditValidation.js",
	"_Type": "Action.Type.ODataService.UpdateEntity"
}