
export default function NotificationDetailsNavQueryOptions() {
    return '$select=NotificationDescription,NotificationNumber,NotificationType,PlanningPlant,OrderId,RequiredEndDate,PriorityType,Priority,BreakdownIndicator,HeaderFunctionLocation,HeaderEquipment,NotifPriority/PriorityDescription,NotifPriority/Priority,FunctionalLocation/FuncLocDesc,ObjectKey&$expand=WorkOrder,NotifPriority,MobileStatus,NotifDocuments,NotifGeometries,NotifGeometries/Geometry,HeaderLongText,FunctionalLocation,Equipment';
}
